modLoader="javafml"
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="https://github.com/oierbravo/melter-forge-mod/issues"
license="MIT"

[[mods]] #mandatory
modId="melter" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Melter" #mandatory
logoFile="logo.png" #optional
credits="Code inspirtation from the amazing Create mod" #optional
authors="oierbravo" #optional
description='''
A simple melter block that turn blocks into liquid.
Intended for modpacks. Use as you see fit.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.melter]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.melter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
