modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/oierbravo/melter-forge-mod/issues"
license="MIT"

[[mods]] #mandatory
updateJSONURL = "https://api.modrinth.com/updates/melter/forge_updates.json"
modId="melter" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Melter" #mandatory
logoFile="logo.png" #optional
credits="Code inspirtation from the amazing Create mod" #optional
authors="oierbravo" #optional
description='''
A simple melter block that turn blocks into liquid.

Intended for modpacks. Use as you see fit.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.melter]] #optional
    modId="forge"
    mandatory=true
    versionRange="[47.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.melter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
